import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  docsSidebar: [
    {
      type: "doc",
      id: "introducao",
      label: "Introdução",
    },
    {
      type: "category",
      label: "Primeiros passos",
      link: {
        type: "doc",
        id: "primeiros-passos/autorizacao-autenticacao",
      },
      items: [
        {
          label: "1. Autorização e autenticação",
          type: "doc",
          id: "primeiros-passos/autorizacao-autenticacao",
        },
        {
          label: "2. Notificações (webhook)",
          type: "doc",
          id: "primeiros-passos/notificacoes",
        },
        {
          label: "3. Dados iniciais",
          type: "doc",
          id: "primeiros-passos/cadastro-dados-iniciais",
        },
        {
          label: "4. Criar viagem",
          type: "category",
          link: {
            type: "doc",
            id: "primeiros-passos/criar-viagem",
          },
          items: [
            {
              label: "4.1. Retorno do envio da viagem",
              type: "doc",
              id: "primeiros-passos/notificacao-viagem",
            },
          ],
          collapsed: true,
        },
        {
          label: "5. Envio do CT-e",
          type: "category",
          link: {
            type: "doc",
            id: "primeiros-passos/envio-cte",
          },
          items: [
            {
              label: "5.1. Notificação do processamento do CT-e",
              type: "doc",
              id: "primeiros-passos/notificacao-processamento-cte",
            },
            {
              label: "5.2. Notificação da conciliação do CT-e",
              type: "doc",
              id: "primeiros-passos/notificacao-conciliacao-cte",
            },
          ],
          collapsed: true,
        },

        {
          label: "6. Fatura",
          type: "category",
          link: {
            type: "doc",
            id: "primeiros-passos/fatura",
          },
          items: [
            {
              label: "6.1. Notificação do faturamento",
              type: "doc",
              id: "primeiros-passos/notificacao-fatura",
            }
          ],
          collapsed: true,
        },

        {
          label: "7. Consulta de emissões",
          type: "doc",
          id: "primeiros-passos/emissoes",
        },
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Referência",
      items: [{ type: "autogenerated", dirName: "referencia" }],
      collapsed: true,
    },
  ],
};

export default sidebars;
